GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO "${username}";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "${username}";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "${username}";
