
CREATE TABLE IF NOT EXISTS public.tenants (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tenants
    DROP CONSTRAINT IF EXISTS tenants_pkey;

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.tenants
    DROP CONSTRAINT IF EXISTS uk_4moql6miwoh3w0drxa2gmjbll;

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk_4moql6miwoh3w0drxa2gmjbll UNIQUE (name);

----------------------------------------------------------------------------------------------
CREATE TABLE public.users (
    id integer NOT NULL,
    tenant_id integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.users
    DROP CONSTRAINT IF EXISTS uk_6dotkott2kjsp8vw4d0m25fb7;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    DROP CONSTRAINT IF EXISTS users_pkey;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

